#!/bin/bash
# Copyright 2018 Iglou.eu
# Copyright 2018 Adrien Kara
# license that can be found in the LICENSE file.

# TMPCONF
USER="adrien"
WORK_DIR="/tmp"

# FUNCTIONS
function err() {
    echo "FATAL ERROR: ${1}"
    exit 1
}

function log()
{
    local _buff=""
    local _logTarg=""

    if [[ -z $forceLog ]]; then _logTarg="${workDir}${log_dir}"
    else _logTarg="${forceLog}"; fi

    if [ $1 -eq 1 ]; then _buff="ERROR"
    else _buff="INFO "; fi

    _buff="[${_buff}]:$(date '+%H%M%S-%d%m%y'): ${2}"

    if ! $quietMode; then echo "${_buff}"; fi
    echo "${_buff}" >> "${_logTarg}/gitRabbit.log"

    return ${1}
}

function help()
{
    echo "help"
}

function parsing_args()
{
    while [ $# -ne 0 ]; do
        case "$1" in
            "-q")
                quietMode="true"
                ;;
            "-c")
                shift
                confFile="$1"
                ;;
            "-u")
                shift
                forceUser="$1"
                ;;
            "-w")
                shift
                workDir="$1"
                ;;
            "-l")
                shift
                forceLog="$1"
                ;;
            *)
                echo "Unknown option -- $1"
                help
                exit 1
                ;;
        esac

        shift
    done
}

function parsing_conf()
{
    return 0
}

# VARS
workDir="${WORK_DIR}"
logDir="/log"
confFile=""
quietMode="false"
forceUser="false"
lapereaux=()

# MAIN
parsing_args $@
log 0 "toto"
exit 0
